# Numerical Operations

In [35]:
import numpy as np

a = np.array([1,2,3,4,5]);

print(a+1);

[2 3 4 5 6]


In [36]:
print(a**2);

[ 1  4  9 16 25]


ELEMENT WISE operation

In [37]:
print(a-3);

[-2 -1  0  1  2]


In [38]:
print(a/2);

[0.5 1.  1.5 2.  2.5]


In [39]:
a = np.ones((3,3),dtype='int') * 3;
print(a);

[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [40]:
b = np.diag([6,2,7]);

print(b);

[[6 0 0]
 [0 2 0]
 [0 0 7]]


In [41]:
print(a+b);

[[ 9  3  3]
 [ 3  5  3]
 [ 3  3 10]]


In [42]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]]);

b= np.ones((3,3))+2;

In [43]:
print(a*b); #element wise multiplication

[[ 3.  6.  9.]
 [12. 15. 18.]
 [21. 24. 27.]]


In [44]:
a = np.array([1,2,3,4])
b = np.array([1,2,3,6])

a==b

array([ True,  True,  True, False])

In [45]:
a < b

array([False, False, False,  True])

In [46]:
c = np.array([1,2,3,4]);

np.array_equal(a,c)

True

#### Logical Operations

In [47]:
a = np.array([1,0,1,0], dtype='bool')
b = np.array([0,0,1,1], dtype=bool);

np.logical_and(a,b)

array([False, False,  True, False])

In [48]:
np.logical_or(a,b)

array([ True, False,  True,  True])

In [49]:
a = np.arange(4);

np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [50]:
np.log(a[2])

0.6931471805599453

In [51]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

#### Computing Sums

In [52]:
a = np.array([1,2,3,4]);

np.sum(a)

10

In [53]:
x = np.array([[1,2],[3,4]])

print(x);

[[1 2]
 [3 4]]


In [54]:
x.sum(axis=0) #axis 0 implies col

array([4, 6])

In [55]:
x.sum(axis=1) #axis 1 implies row

array([3, 7])

In [56]:
print(x.min());

1


In [57]:
print(x.max());

4


In [58]:
print(x.argmin()); #index of least element

0


In [59]:
print(x.argmax()); #index of larget element 

3


In [60]:
#it returns true if all vals are true
np.all([True,True,False])

False

In [61]:
#it returns true if atleaset one val is true

np.any([True,True,False])

True

In [62]:
a = np.zeros((3,3));

np.any(a!=0)

False

In [63]:
np.all(a==0)

True

In [64]:
a= np.array([1,2,3,4])
b= np.array([1,2,3,4])+1
c= np.array([1,2,3,4])+2
((a<b) & (b<c)).all()

True

### Statistics

In [65]:
x = np.array([1,2,3,4,1,1]);

x.mean()

2.0

In [66]:
np.median(x)

1.5

In [67]:
x.std()

1.1547005383792515

Example: 

In [68]:
data = np.loadtxt('populations.txt')

In [69]:
data

array([[ 1900., 30000.,  4000., 48300.],
       [ 1901., 47200.,  6100., 48200.],
       [ 1902., 70200.,  9800., 41500.],
       [ 1903., 77400., 35200., 38200.],
       [ 1904., 36300., 59400., 40600.],
       [ 1905., 20600., 41700., 39800.],
       [ 1906., 18100., 19000., 38600.],
       [ 1907., 21400., 13000., 42300.],
       [ 1908., 22000.,  8300., 44500.],
       [ 1909., 25400.,  9100., 42100.],
       [ 1910., 27100.,  7400., 46000.],
       [ 1911., 40300.,  8000., 46800.],
       [ 1912., 57000., 12300., 43800.],
       [ 1913., 76600., 19500., 40900.],
       [ 1914., 52300., 45700., 39400.],
       [ 1915., 19500., 51100., 39000.],
       [ 1916., 11200., 29700., 36700.],
       [ 1917.,  7600., 15800., 41800.],
       [ 1918., 14600.,  9700., 43300.],
       [ 1919., 16200., 10100., 41300.],
       [ 1920., 24700.,  8600., 47300.]])

In [70]:
#These are the cols in file
year, hares, lynxes, carrots = data.T #transpose

In [71]:
print(year)

[1900. 1901. 1902. 1903. 1904. 1905. 1906. 1907. 1908. 1909. 1910. 1911.
 1912. 1913. 1914. 1915. 1916. 1917. 1918. 1919. 1920.]


In [72]:
#Mean population
#considering cols other that 1st col i.e year
population = data[:,1:]
population

array([[30000.,  4000., 48300.],
       [47200.,  6100., 48200.],
       [70200.,  9800., 41500.],
       [77400., 35200., 38200.],
       [36300., 59400., 40600.],
       [20600., 41700., 39800.],
       [18100., 19000., 38600.],
       [21400., 13000., 42300.],
       [22000.,  8300., 44500.],
       [25400.,  9100., 42100.],
       [27100.,  7400., 46000.],
       [40300.,  8000., 46800.],
       [57000., 12300., 43800.],
       [76600., 19500., 40900.],
       [52300., 45700., 39400.],
       [19500., 51100., 39000.],
       [11200., 29700., 36700.],
       [ 7600., 15800., 41800.],
       [14600.,  9700., 43300.],
       [16200., 10100., 41300.],
       [24700.,  8600., 47300.]])

In [73]:
population.std(axis=0) #cols

array([20897.90645809, 16254.59153691,  3322.50622558])

In [74]:
np.argmax(population,axis=1)

array([2, 2, 0, 0, 1, 1, 2, 2, 2, 2, 2, 2, 0, 0, 0, 1, 2, 2, 2, 2, 2])

# Broadcasting

[
 [1,2,3],
 [1,1,1],
 [3,2,2]
]

+

[
 [0,1,2],
 [0,1,2],
 [0,1,2]
]

is same as

[
 [1,2,3],
 [1,1,1],
 [3,2,2]
]

+

[
 [0,1,2], 
]

#it will add 2 more rows to sync up with 
#first matrix<br>

Other Example:

[
[1],
[2],
[3],
[4]
]

+

[
 [0,1,2]
]

is same is

[
[1,2,3,4],
[1,2,3,4],
[1,2,3,4],
[1,2,3,4]
]

+

[
 [0,1,2],
 [0,1,2],
 [0,1,2],
 [0,1,2]
]

#### Tiles

In [75]:
#in 2nd argument 3 is repeat row 3 times and 1
# is repeat col 1 time
a = np.tile(np.arange(3),(3,1))

print(a);

[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [76]:
a = np.tile(np.arange(3),(3,2))

print(a);

[[0 1 2 0 1 2]
 [0 1 2 0 1 2]
 [0 1 2 0 1 2]]


In [77]:
a = np.tile(np.arange(3),(3,1))
print("a is ",a)

b = np.arange(3);

print("b is: ",b);

a+b

a is  [[0 1 2]
 [0 1 2]
 [0 1 2]]
b is:  [0 1 2]


array([[0, 2, 4],
       [0, 2, 4],
       [0, 2, 4]])

In [78]:
a = np.arange(4)

a.shape
print(a)

[0 1 2 3]


In [79]:
a = a[:, np.newaxis] #converts it to 2d array

a.shape

(4, 1)

In [80]:
print(a)

[[0]
 [1]
 [2]
 [3]]


In [81]:
b = np.array([0,1,2,3]);

In [82]:
a+b

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

# Array Shape Manipulations

Flattening

In [83]:
#Converts 2d array to 1d array

a = np.array([[1,2,3],[4,5,6]])
print(a);

[[1 2 3]
 [4 5 6]]


In [84]:
print(a.ravel()); #converted to 1d array

[1 2 3 4 5 6]


In [85]:
print(a.T.ravel()); #transposed 1d array

[1 4 2 5 3 6]


Reshaping
its opposite to flattening

In [86]:
a = np.array([[1,2,3],[4,5,6]])
print(a);
print(id(a))
print(a.shape);

[[1 2 3]
 [4 5 6]]
140664965070240
(2, 3)


In [87]:
b = a.ravel();
print(b)
print(id(b))

[1 2 3 4 5 6]
140664965069440


In [88]:
b=b.reshape(2,3);
print(b)

[[1 2 3]
 [4 5 6]]


In [89]:
#a,b are stored in same mem location

In [90]:
b[0,0]=10
a

array([[10,  2,  3],
       [ 4,  5,  6]])

In [91]:
a = np.arange(4*3*2).reshape(4,3,2);
a.shape

(4, 3, 2)

In [92]:
print(a);

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]

 [[12 13]
  [14 15]
  [16 17]]

 [[18 19]
  [20 21]
  [22 23]]]


In [93]:
#arg1 -> indicates which matrix
#arg2, arg3 are i,j of that matrix
print(a[0,1,1])

3


In [94]:
a = np.arange(4);

a.resize((8,))

print(a)

[0 1 2 3 0 0 0 0]


In [95]:
b = a;
a.resize((4,))

ValueError: ignored