# NumPy

#### Its Majorly used in AI ML DS

### NumPy Arrays
#### Python Objects:
1) It Contains High level objects: Integer,floationg point

2) Containers: Lists, dictionaries internally build so that We can perform mathamatical operations extensively.

#### NumPy Provides:
1) MultiDimension arrays support <br>
2) Closer to hardware(efficiency) <br>
3) Designed for Sci-fi computations <br>
4) Array oriented computing

In [ ]:
import numpy as np

#this creates numpy array from list.
a= np.array([1,2,3]); 

#other way of creating np array
b=np.arange(10);

print(a);

print(b);

[1 2 3]
[0 1 2 3 4 5 6 7 8 9]


#### Why is it useful: Memory Efficient container that provides fast numerical operations

In [ ]:
#py lists

li = list(range(1000));

# %timeit here runs the below statement
# 1000 times and calculates the time 
# in terms of mean and std deviation in time
# and gives the time taken to run per loop

%timeit [i**2 for i in li]

The slowest run took 6.21 times longer than the fastest. This could mean that an intermediate result is being cached.
1000 loops, best of 5: 250 µs per loop


In [ ]:
li = np.arange(1000);
%timeit np.array(i**2 for i in li)

The slowest run took 16.87 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 5: 2.08 µs per loop


Observation: 
np arrays are almost 200 times faster
that python lists.

In [ ]:
# 1-d Array

a = np.array([0,1,2,3,4]);

print(a);

print(type(a));

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [ ]:
# prints dimension

print(a.ndim);

1


In [ ]:
# Shape

print(a.shape);

(5,)


In [ ]:
print(len(a));

5


In [ ]:
# 2-D Array

b = np.array([[1,2,3],[4,5,6]]);

print(b);

print("shape is ",b.shape);

print("Length here is no.of rows",len(b));

print("Dimension ",b.ndim);

[[1 2 3]
 [4 5 6]]
shape is  (2, 3)
Length here is no.of rows 2
Dimension  2


In [ ]:
# 3-D Array or n-D Array or Tensor

c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])

print(c);

print("shape is ",c.shape);

print("Length here is no.of rows",len(c));

print("Dimension ",c.ndim);


[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
shape is  (2, 2, 2)
Length here is no.of rows 2
Dimension  3


# Creating np array using predefined Functions

In [ ]:
#arange()

a = np.arange(10);

#start, end, step size
b = np.arange(1,8,2);

print(a,"\n",b);

[0 1 2 3 4 5 6 7 8 9] 
 [1 3 5 7]


In [ ]:
# Dividing line into pieces

#start, end, no.of points on line
c = np.linspace(0,1,6)

print(c);

[0.  0.2 0.4 0.6 0.8 1. ]


In [ ]:
# one matrix

#3x3 matrix
d = np.ones((3,3))

print(d);

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
# Zero Matrix

e = np.zeros((4,4));

print(e);

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
# Identity matrix

f = np.eye(3);

print(f);

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
f = np.eye(2,3);

print(f);

[[1. 0. 0.]
 [0. 1. 0.]]


In [ ]:
g = np.diag([1,2,3,4]);

print(g);

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [ ]:
print(np.diag(g));

[1 2 3 4]


In [ ]:
# creating array of rand values

#uniform random number
h = np.random.rand(4);

print(h);

[0.87932003 0.70383285 0.35194259 0.09340424]


### Basic Datatypes

In [ ]:
a = np.arange(10)

print(a.dtype);

int64


In [ ]:
a = np.arange(10, dtype='float')

print(a.dtype);

print(a);

float64
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
d = np.array([1+2j,2+4j])

print(d.dtype);

complex128


# Index and Slicing

In [ ]:
a = np.arange(6);

print(a[0]);

0


In [ ]:
a = np.diag([1,2,3])

print(a[1][1]);

2


In [ ]:
a[1,1]=10;

print(a);

[[ 1  0  0]
 [ 0 10  0]
 [ 0  0  3]]


#### Slicing

In [ ]:
a = np.arange(10);

print(a[1:6:2]);

[1 3 5]


In [ ]:
print(a[2:])


[2 3 4 5 6 7 8 9]


In [ ]:
print(a[0:2]);

[0 1]


In [ ]:
print(a[:])

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
print(a[:3]);

[0 1 2]


In [ ]:
print(a[::-1]); #reverse order

[9 8 7 6 5 4 3 2 1 0]


# Memory Sharing

In [ ]:
a = np.arange(10);

print(a);

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
b = a[::2];

print(b);

[0 2 4 6 8]


In [ ]:
print(np.shares_memory(a,b));

True


Observation: Both a and b share same memory i.e b is subset of a it access the elements form a's memory location, internally a view is created from that b will access the values of a.

In [ ]:
b[0]=77;

print(b);

print(a);

[77  2  4  6  8]
[77  1  2  3  4  5  6  7  8  9]


Obeseravtion: if we modify 'b', 'a' is also modified because they share memory i.e they are in same location.

# Fancy Indexing
np arrays can be indexed with slices, but also with boolean or integer arrays(masks). This method is called fancy indexing. it creates copies not views.

In [ ]:
# it creates 15 rand nums in range 0f 0-20
a = np.random.randint(0,20,15);

print(a);

[18 11 10 15 14  8  5 19 14  3 15  0 12  4 15]


In [ ]:
mask = (a % 2==0);
print(mask);

[ True False  True False  True  True False False  True False False  True
  True  True False]


In [ ]:
# the index which is true 
# that respective value is printed
print(a[mask]); 

[18 10 14  8 14  0 12  4]


Other Example: 

In [ ]:
b = np.array([1,2,3,4,5,6,7,8]);

mask = (b % 2 !=0);

b[mask] = -1;

print(b);

[-1  2 -1  4 -1  6 -1  8]


Observation: Replacing all odd indexed values to -1

#### Indexing with an array of integers

In [ ]:
a = np.arange(0,100,10);

print(a);

#list of indices, i.e values at this indices
# will be present in the list
print(a[[2,3,2,4,2,5]]);



[ 0 10 20 30 40 50 60 70 80 90]
[20 30 20 40 20 50]


In [ ]:
#value at indices 0,3 will be replaced by 77
a[[0,3]]=77;

print(a);

[77 10 20 77 40 50 60 70 80 90]
